name: Daily Research

on:
  schedule:
    - cron: "30 2 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install deps
        run: pip install feedparser newspaper3k lxml_html_clean

      - name: Ensure outputs folder
        run: mkdir -p outputs

      - name: Run script
        run: python run_pipeline.py

      - name: Commit & Push
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git add outputs/

          if git diff --cached --quiet; then
            echo "No changes"
            exit 0
          fi

          git commit -m "daily research"

          git pull --rebase origin main
          git push origin main
